# Generated by Django 4.0.3 on 2022-03-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('razon_social', models.CharField(max_length=50)),
                ('rut', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('dias_visita', models.CharField(max_length=50)),
            ],
        ),
    ]
