# Generated by Django 4.0.3 on 2022-03-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_cliente_celular_proveedor_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='celular',
            field=models.BigIntegerField(default=0),
        ),
    ]
